# Generated by Django 3.2.6 on 2021-08-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_actual_bid_auctionlist_start_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='start_price',
            new_name='price',
        ),
    ]
