# Generated by Django 3.2.6 on 2021-08-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlist_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_category',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='article_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.category'),
            preserve_default=False,
        ),
    ]
