# Generated by Django 3.2.6 on 2021-08-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_watchlist_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(blank=True, to='auctions.AuctionList'),
        ),
    ]
