# Generated by Django 3.2.6 on 2021-08-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_watchlist_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
