# Generated by Django 3.2.6 on 2021-08-26 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='winner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
