# Generated by Django 3.2.6 on 2021-08-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210826_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='winner',
        ),
    ]
