# Generated by Django 3.2.6 on 2021-08-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auctionlist_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='winner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='auctions.user'),
            preserve_default=False,
        ),
    ]
