# Generated by Django 3.2.6 on 2021-08-26 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auctionlist_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='winner',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
